#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x5af47c2, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x6bc3fbc0, __VMLINUX_SYMBOL_STR(__unregister_chrdev) },
	{ 0xb33c8a5a, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x1c39ccce, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0xbcf196b6, __VMLINUX_SYMBOL_STR(__pm_runtime_idle) },
	{ 0xfbc74f64, __VMLINUX_SYMBOL_STR(__copy_from_user) },
	{ 0x22e1ae6f, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xfdd4acfe, __VMLINUX_SYMBOL_STR(pci_release_region) },
	{ 0xd10c9bb3, __VMLINUX_SYMBOL_STR(mem_map) },
	{ 0xb587f0ad, __VMLINUX_SYMBOL_STR(__pm_runtime_disable) },
	{ 0x67c2fa54, __VMLINUX_SYMBOL_STR(__copy_to_user) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x97ec1ff, __VMLINUX_SYMBOL_STR(_raw_write_lock_irqsave) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0x9b53cebc, __VMLINUX_SYMBOL_STR(seq_open) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0xfff6d263, __VMLINUX_SYMBOL_STR(pci_disable_device) },
	{ 0xb5198b77, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0xb54533f7, __VMLINUX_SYMBOL_STR(usecs_to_jiffies) },
	{ 0xf7802486, __VMLINUX_SYMBOL_STR(__aeabi_uidivmod) },
	{ 0x9c956a0f, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x9a1c5d28, __VMLINUX_SYMBOL_STR(device_destroy) },
	{ 0x353e3fa5, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x8361e18f, __VMLINUX_SYMBOL_STR(__register_chrdev) },
	{ 0xfa2bcf10, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xaaccb859, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xd623d989, __VMLINUX_SYMBOL_STR(__pm_runtime_resume) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x8fd9d66, __VMLINUX_SYMBOL_STR(seq_read) },
	{ 0x3bcc3af2, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0x2e6a2335, __VMLINUX_SYMBOL_STR(__platform_driver_register) },
	{ 0x51e77c97, __VMLINUX_SYMBOL_STR(pfn_valid) },
	{ 0x20b6e8d2, __VMLINUX_SYMBOL_STR(__pv_phys_offset) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x42bba018, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0x455293f6, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0xceed7f85, __VMLINUX_SYMBOL_STR(_raw_write_unlock_irqrestore) },
	{ 0x6f6c9c0, __VMLINUX_SYMBOL_STR(proc_remove) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x2ea91370, __VMLINUX_SYMBOL_STR(PDE_DATA) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0xb6da43d4, __VMLINUX_SYMBOL_STR(pci_set_master) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x6f0036d9, __VMLINUX_SYMBOL_STR(del_timer_sync) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xbbe04cdd, __VMLINUX_SYMBOL_STR(proc_mkdir) },
	{ 0x3744cf36, __VMLINUX_SYMBOL_STR(vmalloc_to_pfn) },
	{ 0x75e63cb6, __VMLINUX_SYMBOL_STR(pci_restore_state) },
	{ 0xd84a830a, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x68f0bf72, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0xb0d753fc, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xd7e4f275, __VMLINUX_SYMBOL_STR(kunmap) },
	{ 0x328a05f1, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x7b0fff21, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x4103d69c, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0xe16b533d, __VMLINUX_SYMBOL_STR(platform_get_resource) },
	{ 0x8ef75419, __VMLINUX_SYMBOL_STR(device_create) },
	{ 0xc8fd727e, __VMLINUX_SYMBOL_STR(mod_timer) },
	{ 0xd9605d4c, __VMLINUX_SYMBOL_STR(add_timer) },
	{ 0xd6b8e852, __VMLINUX_SYMBOL_STR(request_threaded_irq) },
	{ 0x8e865d3c, __VMLINUX_SYMBOL_STR(arm_delay_ops) },
	{ 0xd8ee2f52, __VMLINUX_SYMBOL_STR(__get_page_tail) },
	{ 0x42160169, __VMLINUX_SYMBOL_STR(flush_workqueue) },
	{ 0x4075c37e, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0xff6e2167, __VMLINUX_SYMBOL_STR(pci_clear_master) },
	{ 0x62960362, __VMLINUX_SYMBOL_STR(vm_insert_page) },
	{ 0xe2e22abe, __VMLINUX_SYMBOL_STR(find_vma) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0xcd89f3d1, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xf934dbd6, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0xbc10dd97, __VMLINUX_SYMBOL_STR(__put_user_4) },
	{ 0x685bdd58, __VMLINUX_SYMBOL_STR(kmap) },
	{ 0xc748eca5, __VMLINUX_SYMBOL_STR(pm_runtime_enable) },
	{ 0x28ef0f82, __VMLINUX_SYMBOL_STR(get_user_pages) },
	{ 0x3bd1b1f6, __VMLINUX_SYMBOL_STR(msecs_to_jiffies) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xc2165d85, __VMLINUX_SYMBOL_STR(__arm_iounmap) },
	{ 0x8a7d1c31, __VMLINUX_SYMBOL_STR(high_memory) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0x7f24de73, __VMLINUX_SYMBOL_STR(jiffies_to_usecs) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xf98e88cf, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x7afa89fc, __VMLINUX_SYMBOL_STR(vsnprintf) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xb8d3fed1, __VMLINUX_SYMBOL_STR(cpu_cache) },
	{ 0x7cef1f83, __VMLINUX_SYMBOL_STR(pci_set_power_state) },
	{ 0x6357f8a8, __VMLINUX_SYMBOL_STR(proc_create_data) },
	{ 0x27b51bb4, __VMLINUX_SYMBOL_STR(vm_insert_mixed) },
	{ 0x4bea3c21, __VMLINUX_SYMBOL_STR(seq_lseek) },
	{ 0x28d6861d, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x499cb58c, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x743ea1f9, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0xfca84d55, __VMLINUX_SYMBOL_STR(class_destroy) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0x40a7d709, __VMLINUX_SYMBOL_STR(pci_get_device) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xfb961d14, __VMLINUX_SYMBOL_STR(__arm_ioremap) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x216b4302, __VMLINUX_SYMBOL_STR(pci_choose_state) },
	{ 0xb9a340d6, __VMLINUX_SYMBOL_STR(seq_release) },
	{ 0x2529bcd, __VMLINUX_SYMBOL_STR(platform_get_irq) },
	{ 0xdec1693d, __VMLINUX_SYMBOL_STR(vmalloc_to_page) },
	{ 0xcadfbcbf, __VMLINUX_SYMBOL_STR(platform_driver_unregister) },
	{ 0x5541ea93, __VMLINUX_SYMBOL_STR(on_each_cpu) },
	{ 0xc975f150, __VMLINUX_SYMBOL_STR(pci_enable_device) },
	{ 0xac8f37b2, __VMLINUX_SYMBOL_STR(outer_cache) },
	{ 0x6548b408, __VMLINUX_SYMBOL_STR(__class_create) },
	{ 0x8284e69, __VMLINUX_SYMBOL_STR(pci_request_region) },
	{ 0xf20dabd8, __VMLINUX_SYMBOL_STR(free_irq) },
	{ 0xfc2b523b, __VMLINUX_SYMBOL_STR(pci_save_state) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

MODULE_ALIAS("of:N*T*Cti,sgx*");

MODULE_INFO(srcversion, "533BB7E5866E52F63B9ACCB");
